package com.zert.fitness.ui.theme

import androidx.compose.ui.graphics.Color

val LightPrimary = Color(0xFF0059c6)
val LightOnPrimary = Color(0xFFffffff)
val LightPrimaryContainer = Color(0xFFd9e2ff)
val LightOnPrimaryContainer = Color(0xFF001a43)
val LightSecondary = Color(0xFF575e71)
val LightOnSecondary = Color(0xFFffffff)
val LightSecondaryContainer = Color(0xFFdbe2f9)
val LightOnSecondaryContainer = Color(0xFF141b2c)
val LightTertiary = Color(0xFF725573)
val LightOnTertiary = Color(0xFFffffff)
val LightTertiaryContainer = Color(0xFFfcd7fb)
val LightOnTertiaryContainer = Color(0xFF2a132d)
val LightError = Color(0xFFba1a1a)
val LightOnError = Color(0xFFffffff)
val LightErrorContainer = Color(0xFFffdad6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFfefbff)
val LightOnBackground = Color(0xFF1b1b1f)
val LightSurface = Color(0xFFfefbff)
val LightOnSurface = Color(0xFF1b1b1f)
val LightOutline = Color(0xFF757780)
val LightSurfaceVariant = Color(0xFFe1e2ec)
val LightOnSurfaceVariant = Color(0xFF44474f)

val DarkPrimary = Color(0xFFafc6ff)
val DarkOnPrimary = Color(0xFF002d6c)
val DarkPrimaryContainer = Color(0xFF004398)
val DarkOnPrimaryContainer = Color(0xFFd9e2ff)
val DarkSecondary = Color(0xFFbfc6dc)
val DarkOnSecondary = Color(0xFF293042)
val DarkSecondaryContainer = Color(0xFF3f4759)
val DarkOnSecondaryContainer = Color(0xFFdbe2f9)
val DarkTertiary = Color(0xFFdfbbde)
val DarkOnTertiary = Color(0xFF402843)
val DarkTertiaryContainer = Color(0xFF583e5a)
val DarkOnTertiaryContainer = Color(0xFFfcd7fb)
val DarkError = Color(0xFFffb4ab)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000a)
val DarkOnErrorContainer = Color(0xFFffdad6)
val DarkBackground = Color(0xFF1b1b1f)
val DarkOnBackground = Color(0xFFe3e2e6)
val DarkSurface = Color(0xFF1b1b1f)
val DarkOnSurface = Color(0xFFe3e2e6)
val DarkOutline = Color(0xFF8f9099)
val DarkSurfaceVariant = Color(0xFF44474f)
val DarkOnSurfaceVariant = Color(0xFFc5c6d0)